import { mulish } from "@/fonts/fonts";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang="fr">
      <body className={mulish.variable}>{children}</body>
    </html>
  );
}
